require: rubocop-rspec

AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'spec/internal/**/*'
    - 'curation_concerns-models/app/models/concerns/curation_concerns/generic_file/export.rb'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'curation_concerns-models/app/services/curation_concerns/generic_file_audit_service.rb'
    - 'app/controllers/concerns/curation_concerns/generic_files_controller_behavior.rb'
    - 'app/helpers/curation_concerns/curation_concerns_helper_behavior.rb'
    - 'app/helpers/curation_concerns/attribute_helper.rb'
    - 'curation_concerns-models/app/actors/curation_concerns/generic_file_actor.rb'
    - 'curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'curation_concerns-models/app/services/curation_concerns/generic_file_audit_service.rb'
    - 'app/controllers/concerns/curation_concerns/generic_files_controller_behavior.rb'
    - 'app/helpers/curation_concerns/curation_concerns_helper_behavior.rb'
    - 'app/helpers/curation_concerns/attribute_helper.rb'
    - 'curation_concerns-models/app/actors/curation_concerns/generic_file_actor.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/generators/curation_concerns/templates/catalog_controller.rb'
    - 'curation_concerns-models/app/models/datastreams/fits_datastream.rb'
    - 'curation_concerns-models/app/actors/curation_concerns/generic_file_actor.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/controllers/concerns/curation_concerns/users_controller_behavior.rb'
    - 'app/controllers/concerns/curation_concerns/catalog_controller.rb'
    - 'app/controllers/concerns/curation_concerns/generic_files_controller_behavior.rb'
    - 'app/helpers/curation_concerns/curation_concerns_helper_behavior.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/AccessorMethodName:
  Exclude:
    - 'app/controllers/concerns/curation_concerns/curation_concern_controller.rb'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'lib/generators/curation_concerns/templates/catalog_controller.rb'

Style/LineEndConcatenation:
  Exclude:
    - 'spec/test_app_templates/lib/generators/**/*'
    - 'curation_concerns-models/lib/generators/**/*'

Style/PredicateName:
  Exclude:
    - 'app/helpers/curation_concerns/curation_concerns_helper_behavior.rb'
    - 'app/controllers/concerns/curation_concerns/controller.rb'
    - 'app/helpers/curation_concerns/collections_helper.rb'

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'
    - 'spec/jobs/event_jobs_spec.rb'
    - 'curation_concerns-models/lib/generators/curation_concerns/models/templates/config/redis_config.rb'
    - 'curation_concerns-models/lib/curation_concerns/models/active_record/redis.rb'
    - 'curation_concerns-models/lib/curation_concerns/models/active_fedora/redis.rb'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'curation_concerns-models/lib/curation_concerns/models.rb'
    - 'curation_concerns-models/lib/curation_concerns/models/engine.rb'
    - 'curation_concerns-models/app/models/concerns/curation_concerns/generic_file/versions.rb'

Style/SignalException:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'
    - 'curation_concerns-models/lib/generators/**/*'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/jasmine_spec.rb'
    - 'spec/tasks/rake_spec.rb'
    - 'spec/jobs/event_jobs_spec.rb'
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'
