language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - RAILS_VERSION=4.2.7
      RDF_VERSION=1.99.1
    - RAILS_VERSION=5.0.0
      RDF_VERSION=2.1.0
notifications:
  irc:
    channels:
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
before_install:
  - gem uninstall -i /home/travis/.rvm/gems/ruby-2.3.1@global bundler -v 1.13.0
  - gem install bundler -v 1.12.5
before_script:
  - jdk_switcher use oraclejdk8
